[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
ffi = true
fs_permissions = [{access = "read-write", path = "./"}]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "v4-core/=lib/v4-periphery/lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "nitrolite/=../nitrolite/contract/src/",
]

[rpc_endpoints]
base_sepolia = "${TESTNET_RPC_URL}"
unichain_sepolia = "https://sepolia.unichain.org"
